name: joshespi

services:
  joshespi_app:
    build: .
    container_name: joshespi_app
    restart: unless-stopped
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./src:/var/www/html
      - ./.env:/var/www/html/.env:ro
    networks:
      - joshespi_net

  joshespi_nginx:
    image: nginx:alpine
    container_name: joshespi_nginx
    restart: unless-stopped
    ports:
      - "0.0.0.0:8081:80"
    volumes:
      - ./src/public:/var/www/html/public:ro
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - joshespi_app
    networks:
      - joshespi_net

  node:
    image: node:24-alpine
    working_dir: /app
    volumes:
      - ./src:/app
    profiles: ["build"]
    command: ["npm", "run", "build"]

networks:
  joshespi_net:
