memory_limit = 1G

; Security
expose_php = Off
session.cookie_httponly = On
session.cookie_secure = On
session.use_strict_mode = 1

; Uploads
upload_max_filesize = 512M
post_max_size = 512M
max_execution_time = 300
